=== josfernandez-clgx/PowerEditor/trunk/modules/server/src/main/webapp/reports/schema/sample-audit-report.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- =================================================================
	XML Schema Definition of PowerEditor Audit Report.
	
	(c) Copyright 2007 MDA MindBox, Inc. All rights reserved.
	================================================================= -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xsd:element name="audit-report">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="audit-event" minOccurs="0" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="type" type="eventType" />
							<xsd:element name="audit-date" type="xsd:dateTime" />
							<xsd:element name="username" type="xsd:string" />
							<xsd:element name="description" type="xsd:string" minOccurs="0" />
							<xsd:element ref="change-details" minOccurs="0" maxOccurs="unbounded" />
						</xsd:sequence>
						<xsd:attribute name="auditID" type="xsd:integer" use="required" />
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="error-message" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="summary">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="report-date" type="xsd:dateTime" />
							<xsd:element name="audit-event-count" type="xsd:integer" />
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="change-details">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="changed-element" type="changed-element" />
				<xsd:element name="change-detail" type="change-detail" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="changed-element">
		<xsd:sequence>
			<xsd:element name="usage-type" type="xsd:string" minOccurs="0" />
			<xsd:element name="template-name" type="xsd:string" minOccurs="0" />
			<xsd:element name="activation-date" type="xsd:dateTime" minOccurs="0" />
			<xsd:element name="activation-date-name" type="xsd:string" minOccurs="0" />
			<xsd:element name="expiration-date" type="xsd:dateTime" minOccurs="0" />
			<xsd:element name="expiration-date-name" type="xsd:string" minOccurs="0" />
			<xsd:element name="context" type="xsd:string" minOccurs="0" />
		</xsd:sequence>
		<xsd:attribute name="kbAuditID" type="xsd:integer" use="required" />
		<xsd:attribute name="type" type="xsd:string" use="required" />
		<xsd:attribute name="name" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="change-detail">
		<xsd:sequence>
			<xsd:element name="change-type" type="xsd:string" />
			<xsd:element name="change-description" type="xsd:string" />
			<xsd:element name="property-name" type="xsd:string" minOccurs="0" /> <!-- For entity property changes -->
			<xsd:element name="previous-value" type="xsd:string" minOccurs="0" /> <!-- For property/cell value changes -->
			<xsd:element name="new-value" type="xsd:string" minOccurs="0" /> <!-- For property/cell value changes -->
			<xsd:element name="row-number" type="xsd:string" minOccurs="0" /> <!-- For cell value changes -->
			<xsd:element name="column-name" type="xsd:string" minOccurs="0" /> <!-- For cell value changes -->
			<xsd:element name="template" type="xsd:string" minOccurs="0" />
			<xsd:element name="source" type="xsd:string" minOccurs="0" />
			<xsd:element name="effective-date" type="xsd:string" minOccurs="0" />
			<xsd:element name="expiration-date" type="xsd:string" minOccurs="0" />
			<xsd:element name="context-element" type="xsd:string" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="eventType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Logon" />
			<xsd:enumeration value="Logoff" />
			<xsd:enumeration value="Server Startup" />
			<xsd:enumeration value="Server Shutdown" />
			<xsd:enumeration value="KB Modification" />
			<xsd:enumeration value="Deployment Started" />
			<xsd:enumeration value="Deployment Completed" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== josfernandez-clgx/PowerEditor/trunk/modules/dist/content/config/sample-audit-report.xml
<?xml version="1.0" encoding="UTF-8"?>
<audit-report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="sample-audit-report.xsd">
	<audit-event date="2006-01-01T09:00:00" type="Server Startup" username="SYSTEM" />
	<audit-event date="2006-01-01T12:00:00" type="Logon" username="Demo" />
	<audit-event date="2006-01-01T12:10:00" type="KB Modification" username="Demo">
		<change-details>
			<changed-element name="Brand New Client ID" type="client-id"></changed-element>
			<change-detail>
				<change-type>Add Entity</change-type>
				<change-description>Added 'Brand New Client ID'</change-description>
				<client-id>1234567</client-id>
			</change-detail>
		</change-details>
	</audit-event>
	<!-- 
		This corresponds to Use Case 3.1 in Dan's document. 
	-->
	<audit-event date="2007-01-01T12:10:00" type="KB Modification" username="Demo">
		<change-details>
			<changed-element name="" type="guideline">
				<template-name>LTV Credit Score Limit</template-name>
				<guideline-type>Credit-Eval</guideline-type>
				<activation-date>2007-01-01T00:00:00</activation-date>
				<context>
					<client-id-category>15 Yr Fixed</client-id-category>
				</context>
			</changed-element>
			<change-detail>
				<change-type>Add Context Element</change-type>
				<change-description>
					Added '30 Yr Fixed' context element to guideline template 'LTV Credit Score Limit (Type:Credit-Eval)
				</change-description>
				<client-id-category>30 Yr Fixed</client-id-category>
			</change-detail>
		</change-details>
	</audit-event>
	<!-- 
		This corresponds to Use Case 3.7 in Dan's document. 
	-->
	<audit-event date="2007-01-01T12:20:00" type="KB Modification" username="Demo">
		<change-details>
			<changed-element name="" type="guideline">
				<template-name>LTV Credit Score Limit</template-name>
				<guideline-type>Credit-Eval</guideline-type>
				<activation-date>2007-01-01T00:00:00</activation-date>
				<context>
					<client-id-category>15 Yr Fixed</client-id-category>
					<client-id-category>30 Yr Fixed</client-id-category>
				</context>
			</changed-element>
			<change-detail>
				<change-type>Modify Grid Cell</change-type>
				<change-description>
					Changed row 5, column LTV of activation 'LTV Credit Score Limit (Type: Credit-Eval) - date synonym 1
					– date syn 2' from 95.1 to 96.0
				</change-description>
				<previous-value>95.1</previous-value>
				<new-value>96.0</new-value>
				<row-number>5</row-number>
				<column-name>LTV</column-name>
			</change-detail>
			<change-detail>
				<change-type>Modify Grid Cell</change-type>
				<change-description>
					Changed row 6, column LTV of activation 'LTV Credit Score Limit (Type: Credit-Eval) - date synonym 1
					– date syn 2' from 86.0 to 85.0
				</change-description>
				<previous-value>86.0</previous-value>
				<new-value>85.0</new-value>
				<row-number>6</row-number>
				<column-name>LTV</column-name>
			</change-detail>
		</change-details>
	</audit-event>
	<audit-event date="2006-01-01T12:00:00" type="Logoff" username="Demo" />
	<summary>
		<report-date>2001-12-31T12:00:00</report-date>
		<audit-event-count>6</audit-event-count>
	</summary>
</audit-report>
